services:
  registry:
    image: registry:3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.rule=Host(`repo.meupc.test`)"
      - "traefik.http.routers.registry.entrypoints=websecure"
      - "traefik.http.services.registry.loadbalancer.server.port=5000"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == meupc
    environment:
      REGISTRY_HTTP_ADDR: :5000
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - ./data:/var/lib/registry
    networks:
      - swarm_overlay

networks:
  swarm_overlay:
    name: swarm_overlay
    external: true
